name: CI/CD Pipeline
on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    # Добавьте этот шаг для установки зависимостей
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: pytest tests/
    
    # Остальные шаги (Docker login, build, push)...